apiVersion: apps/v1
kind: Deployment
metadata:
  name: forseti-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "forseti.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "forseti.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "forseti.frontend.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101       # nginx user en alpine
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend
          image: {{ .Values.frontend.fullImage | default (printf "%s/%s/frontend:%s" .Values.image.registry .Values.image.repository .Values.image.frontendTag) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 10
            periodSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: Service
metadata:
  name: forseti-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "forseti.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "forseti.frontend.selectorLabels" . | nindent 4 }}
