apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forseti-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: forseti
  source:
    repoURL: https://github.com/TARIUS-S-A-S/forseti-devsecops-gitops.git
    targetRevision: main
    path: environments/prod
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: forseti-prod
  # Prod = sync MANUAL (safeguard extra)
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 20
