env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://host.docker.internal:5173
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: http://host.docker.internal:5173
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules:
  - action: INFO
    customMessage: ''
    id: 10015
  - action: INFO
    customMessage: ''
    id: 10027
  - action: INFO
    customMessage: ''
    id: 10096
  - action: WARN
    customMessage: ''
    id: 10021
  - action: WARN
    customMessage: ''
    id: 10038
  - action: WARN
    customMessage: ''
    id: 10020
  - action: INFO
    customMessage: ''
    id: 10063
  - action: INFO
    customMessage: ''
    id: 90003
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: zap-baseline-report.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: zap-baseline-report.json
    reportTitle: ZAP Scanning Report
    template: traditional-json
  type: report
